version: '3.7'

services:
  app:
    image: node:alpine
    user: node
    working_dir: /home/node/app
    expose: 
      - 3000
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    command: npm run dev